### PR TITLE
Call parent:open needed by the AbstractHandler

### PR DESCRIPTION
**Pull request by arthurkirkosa**
As discussed here https://github.com/symfony/symfony/issues/25445#issuecomment-351641035

### CODE REVIEW

**Comment by arthurkirkosa** [comment]
@jenssegers any word on this merge?

**Comment by arthurkirkosa** [comment]
Can you tag a new release as well, please

**Comment by jenssegers** [comment]
Already did ;)

**Comment by arthurkirkosa** [comment]
Thanks

**Pull request merged**
